### ISSUE TITLE
Can you explain, please, the behavior of the dot?

### ISSUE THREAD

**Issue by mxmauro** [Robert-van-Engelen/FastGlobbing#1]
Hi, I really appreciate your work. Was looking for a glob pattern matching using double stars until found this gem.

But I'm having troubles to understand the behavior of the dot character. I'm trying to use the code on Windows but converted to *nix style for convenience.

```javascript
const glob = require("./glob");

glob.dotglob = false;

if (glob.gitignore_glob_match("/windows/system32/reg.exe", "**/.exe")) {
	console.log("match");
}
else {
	console.log("mismatch");
}

glob.dotglob = true;

if (glob.gitignore_glob_match("/windows/system32/reg.exe", "**/.exe")) {
	console.log("match");
}
else {
	console.log("mismatch");
}
```

In both cases, I would expect a mismatch because the base name. Tracing the code, the `**/` loops and ends skipping the dots in both text and pattern in the switch's default.

Is this the expected behavior?

Kind regards,
Mauro.

**Comment by Robert-van-Engelen** [comment]
Hmm. This looks odd to me.
~~~
./match '/windows/system32/reg.exe' '**/.exe'
naive recursive match = N
recursive match       = N
match                 = N
globly match          = N
glob match            = N
gitignore glob match  = Y
~~~

**Comment by Robert-van-Engelen** [comment]
Should be fixed now.

**Comment by mxmauro** [comment]
Thank you. Very much! I'll try it.

Kind regards.

**Comment by Robert-van-Engelen** [comment]
I've made one more small improvement to handle leading / in directory paths when matched with **/foo globs. These changes are tiny modifications to the logic when matching the next character after **/, which caused the issue you saw. Thanks for reporting.

**Comment by mxmauro** [comment]
You are welcome. Saw the code. A minor issue, in the JS version, the comparison is `===` but in the rest, it is `!=`.

I'll give a check on Windows later, adding the `drive-letter colon` at the beginning.

**Comment by mxmauro** [comment]
Hi @Robert-van-Engelen , tested on Windows' paths and worked perfectly.

Just a minor thing: There is a typo in JS code, line 180, it says `text.chatAt` instead of `text.charAt`

Kind regards and thanks again.

**Comment by Robert-van-Engelen** [comment]
OK, fixed.
